# Configurações da JVM usadas pelo Gradle.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Habilita o cache e a execução paralela para builds mais rápidos.
org.gradle.caching=true
org.gradle.parallel=true

# Usa os recursos do AndroidX.
android.useAndroidX=true

# Kotlin code style oficial.
kotlin.code.style=official

# Gera apenas as classes R necessárias por módulo.
android.nonTransitiveRClass=true
